# Generated by Django 4.2.2 on 2023-07-06 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="recipe", name="no_of_likes",),
        migrations.AddField(
            model_name="recipe", name="rating", field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_updated",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 6, 14, 28, 16, 891290)
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 6, 14, 28, 16, 891290)
            ),
        ),
    ]
